server:
  port: 8091 # 修改Tomcat端口号
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://localhost:3306/fdscoming? # 数据库地址
    username: root # 数据库用户名
    password: 123456 # 数据库密码

  web:
    resources:
      static-locations: classpath:/static/, file:/E:/upload/

springdoc:
  api-docs:
    enabled: true # 开启Spring文档
  swagger-ui:
    enabled: true
  # 请求的格式
  default-consumes-media-type: application/json
  # 响应的格式
  default-produces-media-type: application/json

#spring.web.resources.static-locations: classpath:/static/,file:/D/upload/